kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: frontend
  annotations:
    description: Defines how to build the application
    template.alpha.openshift.io/wait-for-ready: "true"
  labels:
    app: frontend
name: frontend
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'frontend:latest'    
  source:
    git:
      uri: https://github.com/snowjet/demo-flask.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.6
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange:
    type: ImageChange