kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-mqocp
data:
  LOG_LEVEL: "INFO"
  PROJECT_NAME: "Sharing"
  IBM_IMAGE_NAME: "ibm.jpg"
  REDHAT_IMAGE_NAME: "redhat.jpg"
  SECRET_IMAGE_LOCATION: "decrypted.enc"